Reservation_Foyer/Controllers/FoyersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Reservation_Foyer.Models;

namespace Reservation_Foyer.Controllers
{
    public class FoyersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FoyersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Foyers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Foyer.ToListAsync());
        }

        // GET: Foyers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foyer = await _context.Foyer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (foyer == null)
            {
                return NotFound();
            }

            return View(foyer);
        }

        // GET: Foyers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Foyers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Foyer foyer)
        {

            _context.Add(foyer);
            _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }

        // GET: Foyers/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foyer = _context.Foyer.Find(id);
            if (foyer == null)
            {
                return NotFound();
            }
            return View(foyer);
        }

        // POST: Foyers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Foyer foyer)
        {

            _context.Update(foyer);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Foyers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foyer = await _context.Foyer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (foyer == null)
            {
                return NotFound();
            }

            return View(foyer);
        }

        // POST: Foyers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var foyer = await _context.Foyer.FindAsync(id);
            if (foyer != null)
            {
                _context.Foyer.Remove(foyer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoyerExists(int id)
        {
            return _context.Foyer.Any(e => e.Id == id);
        }
    }
}

Reservation_Foyer/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Reservation_Foyer.Models;
using System.Security.Cryptography;
using System.Text;

namespace Reservation_Foyer.Controllers
{
    public class LoginController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LoginController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        // GET: Login
        public IActionResult Login()
        {
            return View();
        }
        // POST: Login
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(string Email, string Password)
        {
            if (!string.IsNullOrEmpty(Email) && !string.IsNullOrEmpty(Password))
            {
                // Find the user by email
                var user = _context.Users.FirstOrDefault(u => u.Email == Email);


                // If user is found
                if (user != null)
                {
                    // Hash the provided password using the same algorithm used for storing passwords
                    string hashedPassword = GetMd5Hash(Password);

                    // Compare the hashed passwords
                    if (user.Password == hashedPassword)
                    {
                        // Check if the user's role is equal to 1
                        if (user.Role == 1)
                        {
                            // Redirect to home page or any desired page for role 1
                            return RedirectToAction("Index", "Chambres");
                        }
                        else
                        {
                            

                            // Pass the user's Id to the data action method
                            return RedirectToAction("data", "Users", new { id = user.Id });
                        }
                    }
                    else
                    {
                        // Passwords do not match
                        ModelState.AddModelError(string.Empty, "Invalid email or password");
                    }
                }
                else
                {
                    // User not found
                    ModelState.AddModelError(string.Empty, "Invalid email or password");
                }
            }

            // If user is not found or password does not match, return to login page with error
            return View();
        }

        // Method to hash the password using MD5 (same as before)
        private string GetMd5Hash(string input)
        {
            using (MD5 md5Hash = MD5.Create())
            {
                byte[] data = md5Hash.ComputeHash(Encoding.UTF8.GetBytes(input));
                StringBuilder stringBuilder = new StringBuilder();
                for (int i = 0; i < data.Length; i++)
                {
                    stringBuilder.Append(data[i].ToString("x2"));
                }
                return stringBuilder.ToString();
            }
        }

    }
}

Reservation_Foyer/Controllers/UniversitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Reservation_Foyer.Models;

namespace Reservation_Foyer.Controllers
{
    public class UniversitesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UniversitesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Universites
        public async Task<IActionResult> Index()
        {
            return View(await _context.Universites.ToListAsync());
        }

        // GET: Universites/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var universite = await _context.Universites
                .FirstOrDefaultAsync(m => m.Id == id);
            if (universite == null)
            {
                return NotFound();
            }

            return View(universite);
        }

        // GET: Universites/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Universites/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Universite universite)
        {
      
            
                _context.Universites.Add(universite);
                 _context.SaveChangesAsync();
                return RedirectToAction("Index");
        
            
        }

        // GET: Universites/Edit/5
         public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var universite =_context.Universites.Find(id);
            if (universite == null)
            {
                return NotFound();
            }
            return View(universite);
        }
        // POST: Universites/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Universite universite)
        {
            _context.Update(universite);
            _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Universites/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var universite = await _context.Universites
                .FirstOrDefaultAsync(m => m.Id == id);
            if (universite == null)
            {
                return NotFound();
            }

            return View(universite);
        }

        // POST: Universites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var universite = await _context.Universites.FindAsync(id);
            if (universite != null)
            {
                _context.Universites.Remove(universite);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UniversiteExists(int id)
        {
            return _context.Universites.Any(e => e.Id == id);
        }
    }
}

Reservation_Foyer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Reservation_Foyer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Reservation_Foyer.styles.css" asp-append-version="true" />
    <style>
        /* Custom styles for header */
        header {
            background-color: #000;
            color: #fff;
        }

        .navbar-brand {
            font-weight: bold;
            color: #fff; /* text color white */
        }

        .navbar-collapse {
            color: #fff;
            justify-content: space-between;
        }

        .navbar-nav .nav-link {
            color: #fff; /* text color white */
        }

        .logout-button {
            margin-left: auto;
        }

        /* Custom styles for footer */
        footer {
            background-color: #000;
           
            text-align: center;
            color: #fff; /* text color white */
        }
        li{
            color: #fff;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: #fff;">Reservation Foyer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" >
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Chambres" asp-action="Index" style="color: #fff;">Chambres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Foyers" asp-action="Index" style="color: #fff;">Foyers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Universites" asp-action="Index" style="color: #fff;">Universites</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Index" style="color: #fff;">Users</a>
                        </li>
                    </ul>
                 
                    <a asp-controller="Login" asp-action="Login" class="btn btn-danger">Logoutt</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white">
        <div class="container">
            &copy; 2024 - Reservation Foyer
            Développé par <a href="https://www.linkedin.com/in/hlel-med-amine-24ba86299/" class="text-white" target="_blank">Med Amine Hlel</a> et <a href="https://www.linkedin.com/in/ariij-mahmoudi/" class="text-white" target="_blank">Ariij Mahmoudi</a>
            Contactez-nous : <a href="mailto:mohamedhlel321@gmail.com" class="text-white">mohamedhlel321@gmail.com</a>, <a href="mailto:ariij@example.com" class="text-white">ariij@example.com</a>

            
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>